language: php

php:
  - 5.5
  - 5.6
  - 7.0

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-dist --no-interaction
  - travis_retry php -r "copy('.env.example', '.env');"
  - travis_retry php artisan key:generate

script: phpunit

notifications:
  email: false
